### ISSUE TITLE
Replay Buffer not working after return from sleep

### ISSUE THREAD

**Issue by xHyperElectric** [Meachamp/OBS-NoPreventSleep#1]
This plugin works great to allow Windows to go to sleep while replay buffering. However when my system returns from sleep, replay buffer appears to be functioning and is on, but it does not actually work. It requires a restart of OBS to function correctly.

**Comment by Meachamp** [comment]
Apologies for the late fix, just got around to looking at this. 

The root cause is that entering sleep causes the system time to jump and this breaks replay buffer encoding somehow. Didn't look into it too much but I could see it hang while trying to encode the output. 

There's a new release out now that addresses this issue. Seems to work alright even though I'm not totally sure the OBS API functions I call are thread safe. If you see OBS crash when coming out of sleep let me know.

**Comment by stevenxed** [comment]
I've got the same issue as @xHyperElectric. Manually putting windows to sleep while replay buffering works great but it rarely turns back on when returning from sleep. When replay buffer does turn back on, it's a gamble whether OBS can save the replay and in one instance OBS got stuck on 'Stopping Replay Buffer...' and crashed when I tried to close it.
And a cosmetic issue: even though the replay buffer is actually off, the recording/red dot under the OBS tray icon occasionally 'sticks' (visible when replay buffer is off, not visible when replay buffer is on) after resuming from sleep until I toggle it on/off.

Unfortunately the inconsistency with saving replays makes using this plugin a hassle, and @Meachamp it'd be great if you could provide the older version of the plugin, where it just stops the replay buffer on sleep.

This is the log output after resuming from sleep at `13:32:37.444` and after waiting a few minutes for the replay buffer to stop:
```
02:54:04.266: ==== Replay Buffer Start ===========================================
02:54:19.680: Output 'Replay Buffer': stopping
02:54:19.680: Output 'Replay Buffer': Total frames output: 892
02:54:19.680: Output 'Replay Buffer': Total drawn frames: 916 (925 attempted)
02:54:19.680: Output 'Replay Buffer': Number of lagged frames due to rendering lag/stalls: 9 (1.0%)
02:54:19.680: ==== Replay Buffer Stop ============================================
02:54:19.680: Video stopped, number of skipped frames due to encoding lag: 9/923 (1.0%)
...
13:32:37.444: ==== Replay Buffer Start ===========================================
```

Crash log from OBS
```
Unhandled exception: c0000005
Date/Time: 2023-05-05, 13:39:49
Fault address: 7FF9BCAE30DB (c:\program files\obs-studio\bin\64bit\w32-pthreads.dll)
libobs version: 29.0.2 (64-bit)
Windows version: 10.0 build 22621 (release: 22H2; revision: 1635; 64-bit)
CPU: 12th Gen Intel(R) Core(TM) i5-12600K

Thread 6EB4: obs gpu encode thread (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
00000098480CFAB0 00007FF9BCAE30DB 0000020E0F236380 0000020E002D20E4 00000098480CFC70 0000020E7E0D0D40 w32-pthreads.dll!pthread_mutex_lock+0x5b
00000098480CFB40 00007FF9925E75E5 0000020E002D1C8C 0000000000000180 0000000000000001 00007FF9C4C6BE60 obs.dll!video_pause_check+0x15
00000098480CFB70 00007FF99261E808 0000020E7E0D0D40 0000000080002F00 0000020E00000000 000000000000000D obs.dll!gpu_encode_thread+0x2d8
00000098480CFCC0 00007FF9BCAE78B6 0000020E120906E0 0000000000000000 0000000000000000 0000000000000000 w32-pthreads.dll!ptw32_threadStart+0x126
00000098480CFD70 00007FF9C2119363 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ucrtbase.dll!0x7ff9c2119363
00000098480CFDA0 00007FF9C37F26AD 0000000000000000 0000000000000000 0000000000000000 0000000000000000 kernel32.dll!0x7ff9c37f26ad
00000098480CFDD0 00007FF9C4C8A9F8 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ntdll.dll!0x7ff9c4c8a9f8
```

**Comment by xHyperElectric** [comment]
I have the exact same problem @stevenxed. Sometimes after waking from sleep, OBS resumes replay buffering as intended. Still, most of the time the tray icon shows replay buffer is on, but OBS is in a frozen state and I will have to open the application and restart the replay buffer. This plugin is necessary to put Windows to sleep while replay buffering, but it would be nice if it resumed replay buffering after waking from sleep properly.
